<a href="https://colab.research.google.com/github/pkrodev/AI_Tutorial/blob/main/Modele_wyjasnienie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.15.0'

In [2]:
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)


In [3]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

#units to ilośc neuronów
#input_shape oznacza 10 cech charakterystycznych, 10 zmiennych lub 10 kolumn
#Na wykresie byłoby to 10 wejść i 4 neurony (1 wartwa ukryta to te 4 neurony)

In [4]:
model.summary()
#44 bo units=4*input_shape=10+1

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44 (176.00 Byte)
Trainable params: 44 (176.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [5]:
model.add(Dense(units=2))

model.summary()
#2* 4+1 =10
#teraz mamy 2 warstwy ukryte

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54 (216.00 Byte)
Trainable params: 54 (216.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
#W tym momencie trzeba wybrać jaki wynik chcemy uzyskać z naszego modelu
#Jeśli ma to być wynik w postaci:
#-modelu regresji powinniśmy użyć liniowej funkcji aktywacji (linear)
#-modelu zwracającego wynik
#prawdopodobieństwa każdej klasy w modelu należy użyć funkcji sigmoid

In [7]:
from tensorflow.keras.activations import linear

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -2.063438 -2.063438
1 -2.010913 -2.010913
2 -1.958814 -1.958814
3 -1.939118 -1.939118
4 -1.797739 -1.797739

In [8]:
px.line(data, x='data', y='linear',width=800,range_y=[-2,2])

In [9]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -2.063438  0.112702
1 -2.010913  0.118062
2 -1.958814  0.123595
3 -1.939118  0.125745
4 -1.797739  0.142127

In [10]:
px.line(data, x='data', y='sigmoid', width=800, range_y=[-0.5, 1.5])

In [11]:


from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()



data  relu
0 -2.063438   0.0
1 -2.010913   0.0
2 -1.958814   0.0
3 -1.939118   0.0
4 -1.797739   0.0

In [12]:
px.line(data, x='data', y='relu', width=800, range_y=[-0.5, 1.5])

In [13]:

from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()


data      tanh
0 -2.063438 -0.968246
1 -2.010913 -0.964791
2 -1.958814 -0.960999
3 -1.939118 -0.959464
4 -1.797739 -0.946571

In [14]:
px.line(data, x='data', y='tanh', width=800, range_y=[-1.5, 1.5])

In [15]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97 (388.00 Byte)
Trainable params: 97 (388.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy', #musi tak być w klasyfikacji binarnej
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy', #musi tak być w klasyfikacji wieloklasowej
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse') #mse lub mae


# **Klasyfikacja binarna**

In [17]:
data=np.random.randn(1000,150) #1000 tablic po 150 zmiennych w każdej
labels = np.random.randint(2,size=(1000,1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [18]:
data[:3]

array([[-1.52711055e+00, -3.59861510e-01,  6.99666529e-01,
        -9.98679566e-01, -1.35867964e+00,  4.10676500e-01,
        -1.91395965e+00,  1.98743472e-01,  2.03757751e+00,
         7.08521823e-01, -2.04364335e-01, -3.95434207e-01,
         1.46400690e+00, -5.88341320e-01, -5.11847797e-01,
         9.42098154e-01,  1.10996508e+00, -2.13727955e-01,
        -5.11685115e-01,  5.78439247e-01,  5.22381635e-01,
         6.20654458e-01,  1.12006710e+00,  3.07089320e-01,
        -1.32245353e+00, -2.29435498e+00,  1.49228966e+00,
         1.54188307e-01, -1.95954210e+00,  6.88785600e-02,
        -1.24247617e+00, -2.83492244e-01, -8.73775450e-01,
        -4.59012458e-01, -8.83453838e-01, -6.46427881e-01,
         3.32550262e-01,  2.76839788e-01, -1.83859471e-01,
         1.33773238e+00,  2.05969774e-01,  7.23422419e-01,
         1.94797245e-01,  8.43570687e-02, -5.76733979e-02,
        -8.09282284e-01, -2.73741909e+00,  7.42602378e-01,
        -1.25714997e-01, -6.51771220e-02, -7.05412091e-0

In [19]:
labels[:10]

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1]])

In [20]:
model= Sequential()
model.add(Dense(units=32,activation='relu', input_shape=(150,))) #ilośc neuronów to często potęga 2 a funkcja aktywacji to relu żeby uczył się nie liniowych rozwiązań (przestrzeń poszukiwania rozwiązań jest większa)
#na tym etapie mamy 2 warstwy warstwa wejściowa (150) oraz warstwa ukryta (gęsta) to nasze 32 neurony

model.add(Dense(1,activation='sigmoid'))  #ta warstwa przekonwertuje dane otrzymane z warstwy wyżej na wartość prawdopodobieństwa

model.compile(optimizer='rmsprop',
              loss = 'binary_crossentropy',
              metrics=['accuracy'])
model.fit(data,labels,epochs=20)

Epoch 1/20
32/32 [==============================] - 1s 3ms/step - loss: 0.8531 - accuracy: 0.5000
Epoch 2/20
32/32 [==============================] - 0s 4ms/step - loss: 0.7147 - accuracy: 0.5500
Epoch 3/20
32/32 [==============================] - 0s 5ms/step - loss: 0.6532 - accuracy: 0.6140
Epoch 4/20
32/32 [==============================] - 0s 4ms/step - loss: 0.6151 - accuracy: 0.6740
Epoch 5/20
32/32 [==============================] - 0s 4ms/step - loss: 0.5823 - accuracy: 0.7060
Epoch 6/20
32/32 [==============================] - 0s 4ms/step - loss: 0.5544 - accuracy: 0.7370
Epoch 7/20
32/32 [==============================] - 0s 3ms/step - loss: 0.5274 - accuracy: 0.7730
Epoch 8/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5028 - accuracy: 0.7850
Epoch 9/20
32/32 [==============================] - 0s 2ms/step - loss: 0.4779 - accuracy: 0.8160
Epoch 10/20
32/32 [==============================] - 0s 2ms/step - loss: 0.4554 - accuracy: 0.8270
Epoch 11/20
32/32 [

In [21]:
model= Sequential()
model.add(Dense(units=32,activation='relu', input_shape=(150,)))


model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss = 'binary_crossentropy',
              metrics=['accuracy'])
model.fit(data,labels,epochs=20, batch_size=30) #batch_size oznacza rozmiar wsadu, nasza sieć (wagi) będzie aktualizowana po 30 próbek (z 1000)

Epoch 1/20
34/34 [==============================] - 1s 2ms/step - loss: 0.8869 - accuracy: 0.5070
Epoch 2/20
34/34 [==============================] - 0s 2ms/step - loss: 0.7448 - accuracy: 0.5410
Epoch 3/20
34/34 [==============================] - 0s 2ms/step - loss: 0.6766 - accuracy: 0.6000
Epoch 4/20
34/34 [==============================] - 0s 2ms/step - loss: 0.6313 - accuracy: 0.6470
Epoch 5/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5944 - accuracy: 0.6840
Epoch 6/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5648 - accuracy: 0.7260
Epoch 7/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5375 - accuracy: 0.7590
Epoch 8/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5126 - accuracy: 0.7720
Epoch 9/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4890 - accuracy: 0.7970
Epoch 10/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4663 - accuracy: 0.8120
Epoch 11/20
34/34 [

In [22]:
model= Sequential()
model.add(Dense(units=32,activation='relu', input_shape=(150,)))


model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss = 'binary_crossentropy',
              metrics=['accuracy'])
model.fit(data,labels,epochs=20, batch_size=30, validation_split=0.2) #20% naszych danych treningowych idzie na testowe

Epoch 1/20
27/27 [==============================] - 1s 10ms/step - loss: 0.9131 - accuracy: 0.5025 - val_loss: 0.8821 - val_accuracy: 0.4900
Epoch 2/20
27/27 [==============================] - 0s 3ms/step - loss: 0.7494 - accuracy: 0.5387 - val_loss: 0.8244 - val_accuracy: 0.5250
Epoch 3/20
27/27 [==============================] - 0s 3ms/step - loss: 0.6740 - accuracy: 0.5813 - val_loss: 0.7950 - val_accuracy: 0.5050
Epoch 4/20
27/27 [==============================] - 0s 3ms/step - loss: 0.6242 - accuracy: 0.6313 - val_loss: 0.7882 - val_accuracy: 0.4850
Epoch 5/20
27/27 [==============================] - 0s 3ms/step - loss: 0.5854 - accuracy: 0.6662 - val_loss: 0.7885 - val_accuracy: 0.4750
Epoch 6/20
27/27 [==============================] - 0s 3ms/step - loss: 0.5507 - accuracy: 0.7300 - val_loss: 0.7935 - val_accuracy: 0.4850
Epoch 7/20
27/27 [==============================] - 0s 4ms/step - loss: 0.5212 - accuracy: 0.7500 - val_loss: 0.8007 - val_accuracy: 0.4850
Epoch 8/20
27/27 [=

In [23]:
model= Sequential()
model.add(Dense(units=32,activation='relu', input_shape=(150,)))


model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss = 'binary_crossentropy',
              metrics=['accuracy'])
model.fit(data,labels,epochs=20, batch_size=30, validation_split=0.2, verbose=0)

In [24]:
model= Sequential()
model.add(Dense(units=32,activation='relu', input_shape=(150,)))


model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss = 'binary_crossentropy',
              metrics=['accuracy'])
history=model.fit(data,labels,epochs=20, batch_size=30, validation_split=0.2)

Epoch 1/20
27/27 [==============================] - 1s 10ms/step - loss: 0.7999 - accuracy: 0.5025 - val_loss: 0.7897 - val_accuracy: 0.4950
Epoch 2/20
27/27 [==============================] - 0s 4ms/step - loss: 0.7039 - accuracy: 0.5575 - val_loss: 0.7674 - val_accuracy: 0.4950
Epoch 3/20
27/27 [==============================] - 0s 4ms/step - loss: 0.6495 - accuracy: 0.6200 - val_loss: 0.7579 - val_accuracy: 0.5200
Epoch 4/20
27/27 [==============================] - 0s 4ms/step - loss: 0.6043 - accuracy: 0.6750 - val_loss: 0.7538 - val_accuracy: 0.5150
Epoch 5/20
27/27 [==============================] - 0s 4ms/step - loss: 0.5654 - accuracy: 0.7262 - val_loss: 0.7529 - val_accuracy: 0.5250
Epoch 6/20
27/27 [==============================] - 0s 4ms/step - loss: 0.5310 - accuracy: 0.7625 - val_loss: 0.7568 - val_accuracy: 0.5200
Epoch 7/20
27/27 [==============================] - 0s 3ms/step - loss: 0.5002 - accuracy: 0.8050 - val_loss: 0.7625 - val_accuracy: 0.5250
Epoch 8/20
27/27 [=

In [25]:
metrics=history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [26]:
model= Sequential()
model.add(Dense(units=32,activation='relu', input_shape=(150,)))


model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss = 'binary_crossentropy',
              metrics=['accuracy'])
history=model.fit(data,labels,epochs=20, batch_size=30, validation_split=0.2, verbose=1)

Epoch 1/20
27/27 [==============================] - 1s 9ms/step - loss: 0.8173 - accuracy: 0.5188 - val_loss: 0.7885 - val_accuracy: 0.4800
Epoch 2/20
27/27 [==============================] - 0s 4ms/step - loss: 0.7205 - accuracy: 0.5525 - val_loss: 0.7646 - val_accuracy: 0.4850
Epoch 3/20
27/27 [==============================] - 0s 4ms/step - loss: 0.6687 - accuracy: 0.5900 - val_loss: 0.7500 - val_accuracy: 0.5000
Epoch 4/20
27/27 [==============================] - 0s 4ms/step - loss: 0.6258 - accuracy: 0.6325 - val_loss: 0.7433 - val_accuracy: 0.5100
Epoch 5/20
27/27 [==============================] - 0s 4ms/step - loss: 0.5900 - accuracy: 0.6812 - val_loss: 0.7433 - val_accuracy: 0.5250
Epoch 6/20
27/27 [==============================] - 0s 3ms/step - loss: 0.5576 - accuracy: 0.7287 - val_loss: 0.7442 - val_accuracy: 0.5300
Epoch 7/20
27/27 [==============================] - 0s 3ms/step - loss: 0.5285 - accuracy: 0.7600 - val_loss: 0.7474 - val_accuracy: 0.5300
Epoch 8/20
27/27 [==

In [27]:
test_data=np.random.randn(5,150)
test_labels = np.random.randint(2, size=(5,1))

In [28]:
model.predict(test_data) #tam gdzie wartości są powyżej 1/2 przypisujemy 1 poniżej 0

1/1 [==============================] - 0s 105ms/step


array([[0.85821223],
       [0.6402445 ],
       [0.44051751],
       [0.07741094],
       [0.14539513]], dtype=float32)

In [36]:
predictions=model.predict(test_data)
array_class_pred=np.array([])

for i in predictions:
  if i>0.5:
    array_class_pred=np.append(array_class_pred, 1)
  else:
    array_class_pred=np.append(array_class_pred, 0)

print(array_class_pred)
print(model.predict(test_data))

1/1 [==============================] - 0s 23ms/step
[1. 1. 0. 0. 0.]
1/1 [==============================] - 0s 22ms/step
[[0.85821223]
 [0.6402445 ]
 [0.44051751]
 [0.07741094]
 [0.14539513]]


#  **Klasyfikacja wieloklasowa**

In [43]:
data=np.random.random((1000,150))
labels = np.random.randint(10,size=(1000,1))

In [44]:
print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [45]:
data[:3]

array([[0.7791488 , 0.55045185, 0.41533822, 0.41755834, 0.14882496,
        0.50223502, 0.54679535, 0.079425  , 0.94863079, 0.24658495,
        0.43509074, 0.43634395, 0.28690761, 0.168129  , 0.85845132,
        0.40736075, 0.51091548, 0.61263379, 0.73422756, 0.85145435,
        0.45413551, 0.22731051, 0.16441602, 0.65111197, 0.13528422,
        0.46368201, 0.01021767, 0.79079992, 0.19800178, 0.0602024 ,
        0.99828666, 0.24856731, 0.24529833, 0.70048039, 0.73737453,
        0.10663499, 0.44791243, 0.55213319, 0.41517799, 0.4548765 ,
        0.69463736, 0.60885549, 0.07933247, 0.17293455, 0.97478225,
        0.81434211, 0.60240251, 0.74896107, 0.66870195, 0.91751467,
        0.46849863, 0.52071399, 0.19501689, 0.16417297, 0.18742541,
        0.0093972 , 0.81161813, 0.57357261, 0.52762682, 0.70596056,
        0.82466355, 0.68310816, 0.81936446, 0.32207504, 0.73848413,
        0.32744668, 0.31770482, 0.39530425, 0.86429344, 0.40067561,
        0.59353372, 0.87979788, 0.16208954, 0.72

In [46]:
labels[:10]

array([[2],
       [4],
       [2],
       [7],
       [5],
       [4],
       [3],
       [2],
       [7],
       [9]])

In [47]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [56]:

labels[9]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [57]:
model=Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))

model.add(Dense(units=10, activation='softmax')) #ilość neuronów w warstwie wyjściowej w wypadku klasyfikacji wieloklasowej musi być równa ilości klas
#w warstwie wyjściowej klasyfikacji wieloklasowej funkcja aktywacji to softmax pozwala ona zwrócić prawdopodobieństwo tych klas (10 w naszym przypadku)

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
25/25 [==============================] - 1s 10ms/step - loss: 2.3882 - accuracy: 0.0950 - val_loss: 2.3104 - val_accuracy: 0.0800
Epoch 2/30
25/25 [==============================] - 0s 3ms/step - loss: 2.3208 - accuracy: 0.1037 - val_loss: 2.3089 - val_accuracy: 0.1100
Epoch 3/30
25/25 [==============================] - 0s 4ms/step - loss: 2.3067 - accuracy: 0.1187 - val_loss: 2.3076 - val_accuracy: 0.1000
Epoch 4/30
25/25 [==============================] - 0s 4ms/step - loss: 2.2964 - accuracy: 0.1163 - val_loss: 2.3039 - val_accuracy: 0.1050
Epoch 5/30
25/25 [==============================] - 0s 3ms/step - loss: 2.2864 - accuracy: 0.1450 - val_loss: 2.3105 - val_accuracy: 0.0800
Epoch 6/30
25/25 [==============================] - 0s 3ms/step - loss: 2.2773 - accuracy: 0.1375 - val_loss: 2.3123 - val_accuracy: 0.1150
Epoch 7/30
25/25 [==============================] - 0s 4ms/step - loss: 2.2691 - accuracy: 0.1675 - val_loss: 2.3118 - val_accuracy: 0.0850
Epoch 8/30
25/25 [=

In [59]:
test_data=np.random.random((9,150)) #tutaj jest 9 o którym mówię poniżej

model.predict(test_data) #na podstawie 150 cech przypisuje do jednej z 10 klas (i tak 9 razy)

1/1 [==============================] - 0s 24ms/step


array([[0.15926246, 0.05772202, 0.11898542, 0.08340825, 0.09365366,
        0.15403654, 0.10657763, 0.08376083, 0.06944282, 0.07315032],
       [0.04099536, 0.0373715 , 0.07678209, 0.42385635, 0.05378769,
        0.0908384 , 0.07386992, 0.08956634, 0.09027123, 0.02266112],
       [0.05859776, 0.1218804 , 0.15420955, 0.10061779, 0.07149046,
        0.11748765, 0.05652267, 0.13596316, 0.11173774, 0.0714928 ],
       [0.08329111, 0.02143872, 0.21305521, 0.13734055, 0.12337022,
        0.08922201, 0.0479202 , 0.1223238 , 0.11373645, 0.04830164],
       [0.11707876, 0.12177782, 0.08932147, 0.11012633, 0.04083045,
        0.11516727, 0.06870639, 0.13322553, 0.15275517, 0.05101078],
       [0.06312181, 0.09502809, 0.19208041, 0.20096062, 0.04774261,
        0.0676217 , 0.05428248, 0.14941339, 0.09752059, 0.03222834],
       [0.13379961, 0.0424699 , 0.03708532, 0.24620296, 0.06169316,
        0.16275741, 0.04220997, 0.14222156, 0.06389244, 0.06766754],
       [0.11674787, 0.05955454, 0.0665020

In [62]:
predictions=model.predict(test_data)
np.argmax(predictions,axis=1) #zamiast model.predict_classes

1/1 [==============================] - 0s 24ms/step


array([0, 3, 2, 2, 8, 3, 3, 5, 3])

# **Regresja**

In [63]:
data = np.random.random((1000,150))
labels = 50 * np.random.random(1000)

In [71]:
data[:3]

array([[0.55534427, 0.05272603, 0.832502  , 0.72203228, 0.28008678,
        0.47731089, 0.52233474, 0.51709427, 0.25854893, 0.4508415 ,
        0.46477376, 0.29796055, 0.11239015, 0.87185399, 0.29952982,
        0.20101182, 0.04781536, 0.02091514, 0.81065867, 0.95744307,
        0.00499167, 0.64314279, 0.21609045, 0.17318356, 0.2831971 ,
        0.84451149, 0.76062533, 0.22782175, 0.87391509, 0.29202196,
        0.7848069 , 0.4409864 , 0.31552477, 0.56672868, 0.33563204,
        0.21677078, 0.11684953, 0.79100184, 0.63256484, 0.60364927,
        0.12030504, 0.58300455, 0.35616932, 0.95694272, 0.29205491,
        0.21556276, 0.67079065, 0.96290443, 0.01004975, 0.91230304,
        0.21386089, 0.69509848, 0.28125757, 0.20322981, 0.96672458,
        0.07119779, 0.01402748, 0.26500403, 0.22887239, 0.1198735 ,
        0.27525782, 0.49045789, 0.15613785, 0.16832385, 0.00715157,
        0.67776598, 0.75133387, 0.9336244 , 0.40627472, 0.10100866,
        0.09464148, 0.00385066, 0.32700392, 0.42

In [65]:
labels[:10]

array([37.19872535, 43.24797485,  0.81069064, 10.81824557, 21.46310598,
       16.64673552, 33.82489589, 28.60793034,  4.6947712 , 16.66634303])

In [68]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1)) #ilośc neuronów w warstwie wyjściowej musi być równa 1 a funkcja aktywacji liniowa

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 [==============================] - 1s 8ms/step - loss: 658.9868 - val_loss: 558.3625
Epoch 2/30
25/25 [==============================] - 0s 4ms/step - loss: 435.1758 - val_loss: 372.3561
Epoch 3/30
25/25 [==============================] - 0s 3ms/step - loss: 290.6902 - val_loss: 250.3785
Epoch 4/30
25/25 [==============================] - 0s 4ms/step - loss: 224.6692 - val_loss: 212.5974
Epoch 5/30
25/25 [==============================] - 0s 3ms/step - loss: 211.3133 - val_loss: 207.8359
Epoch 6/30
25/25 [==============================] - 0s 3ms/step - loss: 209.8541 - val_loss: 206.2183
Epoch 7/30
25/25 [==============================] - 0s 3ms/step - loss: 209.6095 - val_loss: 207.0141
Epoch 8/30
25/25 [==============================] - 0s 4ms/step - loss: 209.3862 - val_loss: 206.4122
Epoch 9/30
25/25 [==============================] - 0s 3ms/step - loss: 208.3860 - val_loss: 204.5117
Epoch 10/30
25/25 [==============================] - 0s 3ms/step - loss: 208.3023 

In [69]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1)) #ilośc neuronów w warstwie wyjściowej musi być równa 1 a funkcja aktywacji liniowa

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 [==============================] - 1s 9ms/step - loss: 20.2857 - mse: 600.5702 - val_loss: 18.1482 - val_mse: 464.9413
Epoch 2/30
25/25 [==============================] - 0s 3ms/step - loss: 15.1448 - mse: 342.8118 - val_loss: 14.3087 - val_mse: 276.7341
Epoch 3/30
25/25 [==============================] - 0s 3ms/step - loss: 13.0162 - mse: 233.4319 - val_loss: 12.7542 - val_mse: 215.9822
Epoch 4/30
25/25 [==============================] - 0s 3ms/step - loss: 12.6782 - mse: 213.5846 - val_loss: 12.5177 - val_mse: 207.6639
Epoch 5/30
25/25 [==============================] - 0s 3ms/step - loss: 12.6364 - mse: 210.7415 - val_loss: 12.5135 - val_mse: 207.5041
Epoch 6/30
25/25 [==============================] - 0s 3ms/step - loss: 12.6050 - mse: 209.8376 - val_loss: 12.4753 - val_mse: 206.3299
Epoch 7/30
25/25 [==============================] - 0s 4ms/step - loss: 12.5816 - mse: 209.2748 - val_loss: 12.5137 - val_mse: 207.3076
Epoch 8/30
25/25 [==============================

In [70]:
test_data=np.random.random((10,150)) #na podstawie tych danych (ale z data a nie test_data) znajduje wzór i stara się przewidzieć wynik predykcji
model.predict(test_data)

1/1 [==============================] - 0s 56ms/step


array([[22.510782],
       [20.653906],
       [24.902151],
       [26.530106],
       [23.168497],
       [26.392439],
       [24.102125],
       [23.652359],
       [25.704062],
       [21.82335 ]], dtype=float32)

Podsumowując:

-W klasyfikacji binarnej model dostaje dane (w naszym wypadku 1000 danych o 150 cechach) i na podstawie tych danych klasyfikuje labele do odpowiedniej klasy czyli 0 lub 1

-W klasyfikacji wieloklasowej model dostaje dane (w naszym wypadku 1000 danych o 150 cechach) i na podstawie tych danych klasyfikuje labele do odpowiedniej klasy czyli od 0 do 9

-W modelu regresji, model na podstawie danych ( w naszym przypadku 1000 danych o 150 cechach każdy) oraz labeli wyznacza wzór który pozwala obliczyć na podstawie danych testowych wynik